

/** LIKES */
export const LIKE_POST = 'LIKE_POST';

/** COMMENTS */
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';

/** PROBLEMS */
export const ADD_PROBLEM = 'ADD_PROBLEM';
export const REMOVE_PROBLEM = 'REMOVE_PROBLEM';
export const EDIT_PROBLEM = 'EDIT_PROBLEM';


/** AUTH */
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const UNAUTHENTICATE_USER = 'UNAUTHENTICATE_USER';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';


